name: iso_build_dec_2024
on:
  workflow_dispatch:
  #schedule:
    #- cron:  '30 2 * * *'


jobs:

  free-disk-space:
    runs-on: ubuntu-20.04
    steps:

    - name: Free GitHub Actions Disk Space (Ubuntu)
      uses: coder-xiaomo/free-disk-space@main
      with:
        # this might remove tools that are actually needed if set to "true"
        tool-cache: true

        # all of these default to true and will be cleared, so set to "false"
        # if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

  prepare-release:
    runs-on: ubuntu-20.04
    needs: free-disk-space
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YYYYMMDDHHmm'
    outputs:
      release_tag: ${{ steps.time.outputs.time }}
  build-release:
    runs-on: ubuntu-20.04
    needs: [prepare-release]
    strategy:
      matrix:
        EDITION: [gnome]
        BRANCH: [stable]
        SCOPE: [full]
    steps:
      - 
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - 
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          format: 'YY.MM'   
      -
        name: image-build-upload
        uses: manjaro/manjaro-iso-action@main
        with:
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}

          #Added this code below to let the build process point to my branched iso-profiles repo and not the official manjaro one
          iso-profiles-repo: "https://github.com/cfdlad/iso-profiles"
          iso-profiles-branch: "dec_2024_iso-profiles"
          
          version: ${{ steps.time.outputs.time }}-development
          kernel: linux612
          code-name: "Nightly-Build"
          release-tag: ${{ needs.prepare-release.outputs.release_tag }}
      -
        name: rollback
        if: ${{ failure() || cancelled() }}
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ needs.prepare-release.outputs.release_tag }} -y --repo ${{ github.repository }}
